// AUTO-GENERATED by scripts/gen-attack-map.mjs from the MITRE ATT&CK Enterprise
// STIX bundle (v19.1). Do not edit by hand — re-run the script to refresh.

/** Tactics in kill-chain order, straight from the ATT&CK matrix definition. */
export const ATTACK_TACTIC_ORDER: string[] = [
  "Reconnaissance",
  "Resource Development",
  "Initial Access",
  "Execution",
  "Persistence",
  "Privilege Escalation",
  "Stealth",
  "Defense Impairment",
  "Credential Access",
  "Discovery",
  "Lateral Movement",
  "Collection",
  "Command and Control",
  "Exfiltration",
  "Impact"
];

export interface GeneratedTechnique {
  id: string;
  name: string;
  tactics: string[];
  url: string;
  summary: string;
}

export const ATTACK_GENERATED: GeneratedTechnique[] = [
  {
    "id": "T1001",
    "name": "Data Obfuscation",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1001",
    "summary": "Adversaries may obfuscate command and control traffic to make it more difficult to detect."
  },
  {
    "id": "T1003",
    "name": "OS Credential Dumping",
    "tactics": [
      "Credential Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1003",
    "summary": "Adversaries may attempt to dump credentials to obtain account login and credential material, normally in the form of a hash or a clear text password."
  },
  {
    "id": "T1003.001",
    "name": "LSASS Memory",
    "tactics": [
      "Credential Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1003/001",
    "summary": "Adversaries may attempt to access credential material stored in the process memory of the Local Security Authority Subsystem Service (LSASS)."
  },
  {
    "id": "T1005",
    "name": "Data from Local System",
    "tactics": [
      "Collection"
    ],
    "url": "https://attack.mitre.org/techniques/T1005",
    "summary": "Adversaries may search local system sources, such as file systems, configuration files, local databases, virtual machine files, or process memory, to find files of interest and sensitive data prior to Exfiltration."
  },
  {
    "id": "T1006",
    "name": "Direct Volume Access",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1006",
    "summary": "Adversaries may directly access a volume to bypass file access controls and file system monitoring."
  },
  {
    "id": "T1007",
    "name": "System Service Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1007",
    "summary": "Adversaries may try to gather information about registered local system services."
  },
  {
    "id": "T1008",
    "name": "Fallback Channels",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1008",
    "summary": "Adversaries may use fallback or alternate communication channels if the primary channel is compromised or inaccessible in order to maintain reliable command and control and to avoid data transfer thresholds."
  },
  {
    "id": "T1010",
    "name": "Application Window Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1010",
    "summary": "Adversaries may attempt to get a listing of open application windows."
  },
  {
    "id": "T1011",
    "name": "Exfiltration Over Other Network Medium",
    "tactics": [
      "Exfiltration"
    ],
    "url": "https://attack.mitre.org/techniques/T1011",
    "summary": "Adversaries may attempt to exfiltrate data over a different network medium than the command and control channel."
  },
  {
    "id": "T1012",
    "name": "Query Registry",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1012",
    "summary": "Adversaries may interact with the Windows Registry to gather information about the system, configuration, and installed software."
  },
  {
    "id": "T1014",
    "name": "Rootkit",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1014",
    "summary": "Adversaries may use rootkits to hide the presence of programs, files, network connections, services, drivers, and other system components."
  },
  {
    "id": "T1016",
    "name": "System Network Configuration Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1016",
    "summary": "Adversaries may look for details about the network configuration and settings, such as IP and/or MAC addresses, of systems they access or through information discovery of remote systems."
  },
  {
    "id": "T1018",
    "name": "Remote System Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1018",
    "summary": "Adversaries may attempt to get a listing of other systems by IP address, hostname, or other logical identifier on a network that may be used for Lateral Movement from the current system."
  },
  {
    "id": "T1020",
    "name": "Automated Exfiltration",
    "tactics": [
      "Exfiltration"
    ],
    "url": "https://attack.mitre.org/techniques/T1020",
    "summary": "Adversaries may exfiltrate data, such as sensitive documents, through the use of automated processing after being gathered during Collection."
  },
  {
    "id": "T1021",
    "name": "Remote Services",
    "tactics": [
      "Lateral Movement"
    ],
    "url": "https://attack.mitre.org/techniques/T1021",
    "summary": "Adversaries may use Valid Accounts to log into a service that accepts remote connections, such as telnet, SSH, and VNC."
  },
  {
    "id": "T1025",
    "name": "Data from Removable Media",
    "tactics": [
      "Collection"
    ],
    "url": "https://attack.mitre.org/techniques/T1025",
    "summary": "Adversaries may search connected removable media on computers they have compromised to find files of interest."
  },
  {
    "id": "T1027",
    "name": "Obfuscated Files or Information",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1027",
    "summary": "Adversaries may attempt to make an executable or file difficult to discover or analyze by encrypting, encoding, or otherwise obfuscating its contents on the system or in transit."
  },
  {
    "id": "T1027.002",
    "name": "Software Packing",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1027/002",
    "summary": "Adversaries may perform software packing or virtual machine software protection to conceal their code."
  },
  {
    "id": "T1029",
    "name": "Scheduled Transfer",
    "tactics": [
      "Exfiltration"
    ],
    "url": "https://attack.mitre.org/techniques/T1029",
    "summary": "Adversaries may schedule data exfiltration to be performed only at certain times of day or at certain intervals."
  },
  {
    "id": "T1030",
    "name": "Data Transfer Size Limits",
    "tactics": [
      "Exfiltration"
    ],
    "url": "https://attack.mitre.org/techniques/T1030",
    "summary": "An adversary may exfiltrate data in fixed size chunks instead of whole files or limit packet sizes below certain thresholds."
  },
  {
    "id": "T1033",
    "name": "System Owner/User Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1033",
    "summary": "Adversaries may attempt to identify the primary user, currently logged in user, set of users that commonly uses a system, or whether a user is actively using the system."
  },
  {
    "id": "T1036",
    "name": "Masquerading",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1036",
    "summary": "Adversaries may attempt to manipulate features of their artifacts to make them appear legitimate or benign to users and/or security tools."
  },
  {
    "id": "T1037",
    "name": "Boot or Logon Initialization Scripts",
    "tactics": [
      "Persistence",
      "Privilege Escalation"
    ],
    "url": "https://attack.mitre.org/techniques/T1037",
    "summary": "Adversaries may use scripts automatically executed at boot or logon initialization to establish persistence."
  },
  {
    "id": "T1039",
    "name": "Data from Network Shared Drive",
    "tactics": [
      "Collection"
    ],
    "url": "https://attack.mitre.org/techniques/T1039",
    "summary": "Adversaries may search network shares on computers they have compromised to find files of interest."
  },
  {
    "id": "T1040",
    "name": "Network Sniffing",
    "tactics": [
      "Credential Access",
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1040",
    "summary": "Adversaries may passively sniff network traffic to capture information about an environment, including authentication material passed over the network."
  },
  {
    "id": "T1041",
    "name": "Exfiltration Over C2 Channel",
    "tactics": [
      "Exfiltration"
    ],
    "url": "https://attack.mitre.org/techniques/T1041",
    "summary": "Adversaries may steal data by exfiltrating it over an existing command and control channel."
  },
  {
    "id": "T1046",
    "name": "Network Service Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1046",
    "summary": "Adversaries may attempt to get a listing of services running on remote hosts and local network infrastructure devices, including those that may be vulnerable to remote software exploitation."
  },
  {
    "id": "T1047",
    "name": "Windows Management Instrumentation",
    "tactics": [
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1047",
    "summary": "Adversaries may abuse Windows Management Instrumentation (WMI) to execute malicious commands and payloads."
  },
  {
    "id": "T1048",
    "name": "Exfiltration Over Alternative Protocol",
    "tactics": [
      "Exfiltration"
    ],
    "url": "https://attack.mitre.org/techniques/T1048",
    "summary": "Adversaries may steal data by exfiltrating it over a different protocol than that of the existing command and control channel."
  },
  {
    "id": "T1049",
    "name": "System Network Connections Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1049",
    "summary": "Adversaries may attempt to get a listing of network connections to or from the compromised system they are currently accessing or from remote systems by querying for information over the network."
  },
  {
    "id": "T1052",
    "name": "Exfiltration Over Physical Medium",
    "tactics": [
      "Exfiltration"
    ],
    "url": "https://attack.mitre.org/techniques/T1052",
    "summary": "Adversaries may attempt to exfiltrate data via a physical medium, such as a removable drive."
  },
  {
    "id": "T1053",
    "name": "Scheduled Task/Job",
    "tactics": [
      "Execution",
      "Persistence",
      "Privilege Escalation"
    ],
    "url": "https://attack.mitre.org/techniques/T1053",
    "summary": "Adversaries may abuse task scheduling functionality to facilitate initial or recurring execution of malicious code."
  },
  {
    "id": "T1053.005",
    "name": "Scheduled Task",
    "tactics": [
      "Execution",
      "Persistence",
      "Privilege Escalation"
    ],
    "url": "https://attack.mitre.org/techniques/T1053/005",
    "summary": "Adversaries may abuse the Windows Task Scheduler to perform task scheduling for initial or recurring execution of malicious code."
  },
  {
    "id": "T1055",
    "name": "Process Injection",
    "tactics": [
      "Stealth",
      "Privilege Escalation"
    ],
    "url": "https://attack.mitre.org/techniques/T1055",
    "summary": "Adversaries may inject code into processes in order to evade process-based defenses as well as possibly elevate privileges."
  },
  {
    "id": "T1055.012",
    "name": "Process Hollowing",
    "tactics": [
      "Stealth",
      "Privilege Escalation"
    ],
    "url": "https://attack.mitre.org/techniques/T1055/012",
    "summary": "Adversaries may inject malicious code into suspended and hollowed processes in order to evade process-based defenses."
  },
  {
    "id": "T1056",
    "name": "Input Capture",
    "tactics": [
      "Collection",
      "Credential Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1056",
    "summary": "Adversaries may use methods of capturing user input to obtain credentials or collect information."
  },
  {
    "id": "T1057",
    "name": "Process Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1057",
    "summary": "Adversaries may attempt to get information about running processes on a system."
  },
  {
    "id": "T1059",
    "name": "Command and Scripting Interpreter",
    "tactics": [
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1059",
    "summary": "Adversaries may abuse command and script interpreters to execute commands, scripts, or binaries."
  },
  {
    "id": "T1068",
    "name": "Exploitation for Privilege Escalation",
    "tactics": [
      "Privilege Escalation"
    ],
    "url": "https://attack.mitre.org/techniques/T1068",
    "summary": "Adversaries may exploit software vulnerabilities in an attempt to elevate privileges."
  },
  {
    "id": "T1069",
    "name": "Permission Groups Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1069",
    "summary": "Adversaries may attempt to discover group and permission settings."
  },
  {
    "id": "T1070",
    "name": "Indicator Removal",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1070",
    "summary": "Adversaries may selectively delete or modify artifacts generated to reduce indications of their presence and blend in with legitimate activity."
  },
  {
    "id": "T1070.006",
    "name": "Timestomp",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1070/006",
    "summary": "Adversaries may modify file time attributes to hide new files or changes to existing files."
  },
  {
    "id": "T1071",
    "name": "Application Layer Protocol",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1071",
    "summary": "Adversaries may communicate using OSI application layer protocols to avoid detection/network filtering by blending in with existing traffic."
  },
  {
    "id": "T1071.004",
    "name": "DNS",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1071/004",
    "summary": "Adversaries may communicate using the Domain Name System (DNS) application layer protocol to avoid detection/network filtering by blending in with existing traffic."
  },
  {
    "id": "T1072",
    "name": "Software Deployment Tools",
    "tactics": [
      "Execution",
      "Lateral Movement"
    ],
    "url": "https://attack.mitre.org/techniques/T1072",
    "summary": "Adversaries may gain access to and use centralized software suites installed within an enterprise to execute commands and move laterally through the network."
  },
  {
    "id": "T1074",
    "name": "Data Staged",
    "tactics": [
      "Collection"
    ],
    "url": "https://attack.mitre.org/techniques/T1074",
    "summary": "Adversaries may stage collected data in a central location or directory prior to Exfiltration."
  },
  {
    "id": "T1078",
    "name": "Valid Accounts",
    "tactics": [
      "Stealth",
      "Persistence",
      "Privilege Escalation",
      "Initial Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1078",
    "summary": "Adversaries may obtain and abuse credentials of existing accounts as a means of gaining Initial Access, Persistence, Privilege Escalation, or Defense Evasion."
  },
  {
    "id": "T1080",
    "name": "Taint Shared Content",
    "tactics": [
      "Lateral Movement"
    ],
    "url": "https://attack.mitre.org/techniques/T1080",
    "summary": "Adversaries may deliver payloads to remote systems by adding content to shared storage locations, such as network drives or internal code repositories."
  },
  {
    "id": "T1082",
    "name": "System Information Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1082",
    "summary": "An adversary may attempt to get detailed information about the operating system and hardware, including version, patches, hotfixes, service packs, and architecture."
  },
  {
    "id": "T1083",
    "name": "File and Directory Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1083",
    "summary": "Adversaries may enumerate files and directories or may search in specific locations of a host or network share for certain information within a file system."
  },
  {
    "id": "T1087",
    "name": "Account Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1087",
    "summary": "Adversaries may attempt to get a listing of valid accounts, usernames, or email addresses on a system or within a compromised environment."
  },
  {
    "id": "T1090",
    "name": "Proxy",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1090",
    "summary": "Adversaries may use a connection proxy to direct network traffic between systems or act as an intermediary for network communications to a command and control server to avoid direct connections to their infrastructure."
  },
  {
    "id": "T1091",
    "name": "Replication Through Removable Media",
    "tactics": [
      "Lateral Movement",
      "Initial Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1091",
    "summary": "Adversaries may move onto systems, possibly those on disconnected or air-gapped networks, by copying malware to removable media and taking advantage of Autorun features when the media is inserted into a system and executes."
  },
  {
    "id": "T1092",
    "name": "Communication Through Removable Media",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1092",
    "summary": "Adversaries can perform command and control between compromised hosts on potentially disconnected networks using removable media to transfer commands from system to system."
  },
  {
    "id": "T1095",
    "name": "Non-Application Layer Protocol",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1095",
    "summary": "Adversaries may use an OSI non-application layer protocol for communication between host and C2 server or among infected hosts within a network."
  },
  {
    "id": "T1098",
    "name": "Account Manipulation",
    "tactics": [
      "Persistence",
      "Privilege Escalation"
    ],
    "url": "https://attack.mitre.org/techniques/T1098",
    "summary": "Adversaries may manipulate accounts to maintain and/or elevate access to victim systems."
  },
  {
    "id": "T1102",
    "name": "Web Service",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1102",
    "summary": "Adversaries may use an existing, legitimate external Web service as a means for relaying data to/from a compromised system."
  },
  {
    "id": "T1104",
    "name": "Multi-Stage Channels",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1104",
    "summary": "Adversaries may create multiple stages for command and control that are employed under different conditions or for certain functions."
  },
  {
    "id": "T1105",
    "name": "Ingress Tool Transfer",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1105",
    "summary": "Adversaries may transfer tools or other files from an external system into a compromised environment."
  },
  {
    "id": "T1106",
    "name": "Native API",
    "tactics": [
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1106",
    "summary": "Adversaries may interact with the native OS application programming interface (API) to execute behaviors."
  },
  {
    "id": "T1110",
    "name": "Brute Force",
    "tactics": [
      "Credential Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1110",
    "summary": "Adversaries may use brute force techniques to gain access to accounts when passwords are unknown or when password hashes are obtained."
  },
  {
    "id": "T1111",
    "name": "Multi-Factor Authentication Interception",
    "tactics": [
      "Credential Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1111",
    "summary": "Adversaries may target multi-factor authentication (MFA) mechanisms, (i.e., smart cards, token generators, etc.) to gain access to credentials that can be used to access systems, services, and network resources."
  },
  {
    "id": "T1112",
    "name": "Modify Registry",
    "tactics": [
      "Defense Impairment",
      "Persistence"
    ],
    "url": "https://attack.mitre.org/techniques/T1112",
    "summary": "Adversaries may interact with the Windows Registry as part of a variety of other techniques to aid in defense evasion, persistence, and execution."
  },
  {
    "id": "T1113",
    "name": "Screen Capture",
    "tactics": [
      "Collection"
    ],
    "url": "https://attack.mitre.org/techniques/T1113",
    "summary": "Adversaries may attempt to take screen captures of the desktop to gather information over the course of an operation."
  },
  {
    "id": "T1114",
    "name": "Email Collection",
    "tactics": [
      "Collection"
    ],
    "url": "https://attack.mitre.org/techniques/T1114",
    "summary": "Adversaries may target user email to collect sensitive information."
  },
  {
    "id": "T1115",
    "name": "Clipboard Data",
    "tactics": [
      "Collection"
    ],
    "url": "https://attack.mitre.org/techniques/T1115",
    "summary": "Adversaries may collect data stored in the clipboard from users copying information within or between applications."
  },
  {
    "id": "T1119",
    "name": "Automated Collection",
    "tactics": [
      "Collection"
    ],
    "url": "https://attack.mitre.org/techniques/T1119",
    "summary": "Once established within a system or network, an adversary may use automated techniques for collecting internal data."
  },
  {
    "id": "T1120",
    "name": "Peripheral Device Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1120",
    "summary": "Adversaries may attempt to gather information about attached peripheral devices and components connected to a computer system."
  },
  {
    "id": "T1123",
    "name": "Audio Capture",
    "tactics": [
      "Collection"
    ],
    "url": "https://attack.mitre.org/techniques/T1123",
    "summary": "An adversary can leverage a computer's peripheral devices (e.g., microphones and webcams) or applications (e.g., voice and video call services) to capture audio recordings for the purpose of listening into sensitive conversations to…"
  },
  {
    "id": "T1124",
    "name": "System Time Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1124",
    "summary": "An adversary may gather the system time and/or time zone settings from a local or remote system."
  },
  {
    "id": "T1125",
    "name": "Video Capture",
    "tactics": [
      "Collection"
    ],
    "url": "https://attack.mitre.org/techniques/T1125",
    "summary": "An adversary can leverage a computer's peripheral devices (e.g., integrated cameras or webcams) or applications (e.g., video call services) to capture video recordings for the purpose of gathering information."
  },
  {
    "id": "T1127",
    "name": "Trusted Developer Utilities Proxy Execution",
    "tactics": [
      "Stealth",
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1127",
    "summary": "Adversaries may take advantage of trusted developer utilities to proxy execution of malicious payloads."
  },
  {
    "id": "T1129",
    "name": "Shared Modules",
    "tactics": [
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1129",
    "summary": "Adversaries may execute malicious payloads via loading shared modules."
  },
  {
    "id": "T1132",
    "name": "Data Encoding",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1132",
    "summary": "Adversaries may encode data to make the content of command and control traffic more difficult to detect."
  },
  {
    "id": "T1133",
    "name": "External Remote Services",
    "tactics": [
      "Persistence",
      "Initial Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1133",
    "summary": "Adversaries may leverage external-facing remote services to initially access and/or persist within a network."
  },
  {
    "id": "T1134",
    "name": "Access Token Manipulation",
    "tactics": [
      "Stealth",
      "Privilege Escalation"
    ],
    "url": "https://attack.mitre.org/techniques/T1134",
    "summary": "Adversaries may modify access tokens to operate under a different user or system security context to perform actions and bypass access controls."
  },
  {
    "id": "T1135",
    "name": "Network Share Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1135",
    "summary": "Adversaries may look for folders and drives shared on remote systems as a means of identifying sources of information to gather as a precursor for Collection and to identify potential systems of interest for Lateral Movement."
  },
  {
    "id": "T1136",
    "name": "Create Account",
    "tactics": [
      "Persistence"
    ],
    "url": "https://attack.mitre.org/techniques/T1136",
    "summary": "Adversaries may create an account to maintain access to victim systems."
  },
  {
    "id": "T1137",
    "name": "Office Application Startup",
    "tactics": [
      "Persistence"
    ],
    "url": "https://attack.mitre.org/techniques/T1137",
    "summary": "Adversaries may leverage Microsoft Office-based applications for persistence between startups."
  },
  {
    "id": "T1140",
    "name": "Deobfuscate/Decode Files or Information",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1140",
    "summary": "Adversaries may use Obfuscated Files or Information to hide artifacts of an intrusion from analysis."
  },
  {
    "id": "T1176",
    "name": "Software Extensions",
    "tactics": [
      "Persistence"
    ],
    "url": "https://attack.mitre.org/techniques/T1176",
    "summary": "Adversaries may abuse software extensions to establish persistent access to victim systems."
  },
  {
    "id": "T1185",
    "name": "Browser Session Hijacking",
    "tactics": [
      "Collection"
    ],
    "url": "https://attack.mitre.org/techniques/T1185",
    "summary": "Adversaries may take advantage of security vulnerabilities and inherent functionality in browser software to change content, modify user-behaviors, and intercept information as part of various browser session hijacking techniques."
  },
  {
    "id": "T1187",
    "name": "Forced Authentication",
    "tactics": [
      "Credential Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1187",
    "summary": "Adversaries may gather credential material by invoking or forcing a user to automatically provide authentication information through a mechanism in which they can intercept."
  },
  {
    "id": "T1189",
    "name": "Drive-by Compromise",
    "tactics": [
      "Initial Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1189",
    "summary": "Adversaries may gain access to a system through a user visiting a website over the normal course of browsing."
  },
  {
    "id": "T1190",
    "name": "Exploit Public-Facing Application",
    "tactics": [
      "Initial Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1190",
    "summary": "Adversaries may attempt to exploit a weakness in an Internet-facing host or system to initially access a network."
  },
  {
    "id": "T1195",
    "name": "Supply Chain Compromise",
    "tactics": [
      "Initial Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1195",
    "summary": "Adversaries may manipulate products or product delivery mechanisms prior to receipt by a final consumer for the purpose of data or system compromise."
  },
  {
    "id": "T1197",
    "name": "BITS Jobs",
    "tactics": [
      "Stealth",
      "Persistence",
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1197",
    "summary": "Adversaries may abuse BITS jobs to persistently execute code and perform various background tasks."
  },
  {
    "id": "T1199",
    "name": "Trusted Relationship",
    "tactics": [
      "Initial Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1199",
    "summary": "Adversaries may breach or otherwise leverage organizations who have access to intended victims."
  },
  {
    "id": "T1200",
    "name": "Hardware Additions",
    "tactics": [
      "Initial Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1200",
    "summary": "Adversaries may physically introduce computer accessories, networking hardware, or other computing devices into a system or network that can be used as a vector to gain access."
  },
  {
    "id": "T1201",
    "name": "Password Policy Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1201",
    "summary": "Adversaries may attempt to access detailed information about the password policy used within an enterprise network or cloud environment."
  },
  {
    "id": "T1202",
    "name": "Indirect Command Execution",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1202",
    "summary": "Adversaries may abuse utilities that allow for command execution to bypass security restrictions that limit the use of command-line interpreters."
  },
  {
    "id": "T1203",
    "name": "Exploitation for Client Execution",
    "tactics": [
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1203",
    "summary": "Adversaries may exploit software vulnerabilities in client applications to execute code."
  },
  {
    "id": "T1204",
    "name": "User Execution",
    "tactics": [
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1204",
    "summary": "An adversary may rely upon specific actions by a user in order to gain execution."
  },
  {
    "id": "T1205",
    "name": "Traffic Signaling",
    "tactics": [
      "Stealth",
      "Persistence",
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1205",
    "summary": "Adversaries may use traffic signaling to hide open ports or other malicious functionality used for persistence or command and control."
  },
  {
    "id": "T1207",
    "name": "Rogue Domain Controller",
    "tactics": [
      "Defense Impairment"
    ],
    "url": "https://attack.mitre.org/techniques/T1207",
    "summary": "Adversaries may register a rogue Domain Controller to enable manipulation of Active Directory data."
  },
  {
    "id": "T1210",
    "name": "Exploitation of Remote Services",
    "tactics": [
      "Lateral Movement"
    ],
    "url": "https://attack.mitre.org/techniques/T1210",
    "summary": "Adversaries may exploit remote services to gain unauthorized access to internal systems once inside of a network."
  },
  {
    "id": "T1211",
    "name": "Exploitation for Stealth",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1211",
    "summary": "Adversaries may exploit vulnerabilities to evade detection by hiding activity, suppressing logging, or operating within trusted or unmonitored components."
  },
  {
    "id": "T1212",
    "name": "Exploitation for Credential Access",
    "tactics": [
      "Credential Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1212",
    "summary": "Adversaries may exploit software vulnerabilities in an attempt to collect credentials."
  },
  {
    "id": "T1213",
    "name": "Data from Information Repositories",
    "tactics": [
      "Collection"
    ],
    "url": "https://attack.mitre.org/techniques/T1213",
    "summary": "Adversaries may leverage information repositories to mine valuable information."
  },
  {
    "id": "T1216",
    "name": "System Script Proxy Execution",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1216",
    "summary": "Adversaries may use trusted scripts, often signed with certificates, to proxy the execution of malicious files."
  },
  {
    "id": "T1217",
    "name": "Browser Information Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1217",
    "summary": "Adversaries may enumerate information about browsers to learn more about compromised environments."
  },
  {
    "id": "T1218",
    "name": "System Binary Proxy Execution",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1218",
    "summary": "Adversaries may bypass process and/or signature-based defenses by proxying execution of malicious content with signed, or otherwise trusted, binaries."
  },
  {
    "id": "T1219",
    "name": "Remote Access Tools",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1219",
    "summary": "An adversary may use legitimate remote access tools to establish an interactive command and control channel within a network."
  },
  {
    "id": "T1220",
    "name": "XSL Script Processing",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1220",
    "summary": "Adversaries may bypass application control and obscure execution of code by embedding scripts inside XSL files."
  },
  {
    "id": "T1221",
    "name": "Template Injection",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1221",
    "summary": "Adversaries may create or modify references in user document templates to conceal malicious code or force authentication attempts."
  },
  {
    "id": "T1222",
    "name": "File and Directory Permissions Modification",
    "tactics": [
      "Defense Impairment"
    ],
    "url": "https://attack.mitre.org/techniques/T1222",
    "summary": "Adversaries may modify file or directory permissions/attributes to evade access control lists (ACLs) and access protected files."
  },
  {
    "id": "T1480",
    "name": "Execution Guardrails",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1480",
    "summary": "Adversaries may use execution guardrails to constrain execution or actions based on adversary supplied and environment specific conditions that are expected to be present on the target."
  },
  {
    "id": "T1482",
    "name": "Domain Trust Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1482",
    "summary": "Adversaries may attempt to gather information on domain trust relationships that may be used to identify lateral movement opportunities in Windows multi-domain/forest environments."
  },
  {
    "id": "T1484",
    "name": "Domain or Tenant Policy Modification",
    "tactics": [
      "Defense Impairment",
      "Privilege Escalation"
    ],
    "url": "https://attack.mitre.org/techniques/T1484",
    "summary": "Adversaries may modify the configuration settings of a domain or identity tenant to evade defenses and/or escalate privileges in centrally managed environments."
  },
  {
    "id": "T1485",
    "name": "Data Destruction",
    "tactics": [
      "Impact"
    ],
    "url": "https://attack.mitre.org/techniques/T1485",
    "summary": "Adversaries may destroy data and files on specific systems or in large numbers on a network to interrupt availability to systems, services, and network resources."
  },
  {
    "id": "T1486",
    "name": "Data Encrypted for Impact",
    "tactics": [
      "Impact"
    ],
    "url": "https://attack.mitre.org/techniques/T1486",
    "summary": "Adversaries may encrypt data on target systems or on large numbers of systems in a network to interrupt availability to system and network resources."
  },
  {
    "id": "T1489",
    "name": "Service Stop",
    "tactics": [
      "Impact"
    ],
    "url": "https://attack.mitre.org/techniques/T1489",
    "summary": "Adversaries may stop or disable services on a system to render those services unavailable to legitimate users."
  },
  {
    "id": "T1490",
    "name": "Inhibit System Recovery",
    "tactics": [
      "Impact"
    ],
    "url": "https://attack.mitre.org/techniques/T1490",
    "summary": "Adversaries may delete or remove built-in data and turn off services designed to aid in the recovery of a corrupted system to prevent recovery."
  },
  {
    "id": "T1491",
    "name": "Defacement",
    "tactics": [
      "Impact"
    ],
    "url": "https://attack.mitre.org/techniques/T1491",
    "summary": "Adversaries may modify visual content available internally or externally to an enterprise network, thus affecting the integrity of the original content."
  },
  {
    "id": "T1495",
    "name": "Firmware Corruption",
    "tactics": [
      "Impact"
    ],
    "url": "https://attack.mitre.org/techniques/T1495",
    "summary": "Adversaries may overwrite or corrupt the flash memory contents of system BIOS or other firmware in devices attached to a system in order to render them inoperable or unable to boot, thus denying the availability to use the devices…"
  },
  {
    "id": "T1496",
    "name": "Resource Hijacking",
    "tactics": [
      "Impact"
    ],
    "url": "https://attack.mitre.org/techniques/T1496",
    "summary": "Adversaries may leverage the resources of co-opted systems to complete resource-intensive tasks, which may impact system and/or hosted service availability."
  },
  {
    "id": "T1497",
    "name": "Virtualization/Sandbox Evasion",
    "tactics": [
      "Stealth",
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1497",
    "summary": "Adversaries may employ various means to detect and avoid virtualization and analysis environments."
  },
  {
    "id": "T1498",
    "name": "Network Denial of Service",
    "tactics": [
      "Impact"
    ],
    "url": "https://attack.mitre.org/techniques/T1498",
    "summary": "Adversaries may perform Network Denial of Service (DoS) attacks to degrade or block the availability of targeted resources to users."
  },
  {
    "id": "T1499",
    "name": "Endpoint Denial of Service",
    "tactics": [
      "Impact"
    ],
    "url": "https://attack.mitre.org/techniques/T1499",
    "summary": "Adversaries may perform Endpoint Denial of Service (DoS) attacks to degrade or block the availability of services to users."
  },
  {
    "id": "T1505",
    "name": "Server Software Component",
    "tactics": [
      "Persistence"
    ],
    "url": "https://attack.mitre.org/techniques/T1505",
    "summary": "Adversaries may abuse legitimate extensible development features of servers to establish persistent access to systems."
  },
  {
    "id": "T1518",
    "name": "Software Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1518",
    "summary": "Adversaries may attempt to get a listing of software and software versions that are installed on a system or in a cloud environment."
  },
  {
    "id": "T1525",
    "name": "Implant Internal Image",
    "tactics": [
      "Persistence"
    ],
    "url": "https://attack.mitre.org/techniques/T1525",
    "summary": "Adversaries may implant cloud or container images with malicious code to establish persistence after gaining access to an environment."
  },
  {
    "id": "T1526",
    "name": "Cloud Service Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1526",
    "summary": "An adversary may attempt to enumerate the cloud services running on a system after gaining access."
  },
  {
    "id": "T1528",
    "name": "Steal Application Access Token",
    "tactics": [
      "Credential Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1528",
    "summary": "Adversaries can steal application access tokens as a means of acquiring credentials to access remote systems and resources."
  },
  {
    "id": "T1529",
    "name": "System Shutdown/Reboot",
    "tactics": [
      "Impact"
    ],
    "url": "https://attack.mitre.org/techniques/T1529",
    "summary": "Adversaries may shutdown/reboot systems to interrupt access to, or aid in the destruction of, those systems."
  },
  {
    "id": "T1530",
    "name": "Data from Cloud Storage",
    "tactics": [
      "Collection"
    ],
    "url": "https://attack.mitre.org/techniques/T1530",
    "summary": "Adversaries may access data from cloud storage. Many IaaS providers offer solutions for online data object storage such as Amazon S3, Azure Storage, and Google Cloud Storage."
  },
  {
    "id": "T1531",
    "name": "Account Access Removal",
    "tactics": [
      "Impact"
    ],
    "url": "https://attack.mitre.org/techniques/T1531",
    "summary": "Adversaries may interrupt availability of system and network resources by inhibiting access to accounts utilized by legitimate users."
  },
  {
    "id": "T1534",
    "name": "Internal Spearphishing",
    "tactics": [
      "Lateral Movement"
    ],
    "url": "https://attack.mitre.org/techniques/T1534",
    "summary": "After they already have access to accounts or systems within the environment, adversaries may use internal spearphishing to gain access to additional information or compromise other users within the same organization."
  },
  {
    "id": "T1535",
    "name": "Unused/Unsupported Cloud Regions",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1535",
    "summary": "Adversaries may create cloud instances in unused geographic service regions in order to evade detection."
  },
  {
    "id": "T1537",
    "name": "Transfer Data to Cloud Account",
    "tactics": [
      "Exfiltration"
    ],
    "url": "https://attack.mitre.org/techniques/T1537",
    "summary": "Adversaries may exfiltrate data by transferring the data, including through sharing/syncing and creating backups of cloud environments, to another cloud account they control on the same service."
  },
  {
    "id": "T1538",
    "name": "Cloud Service Dashboard",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1538",
    "summary": "An adversary may use a cloud service dashboard GUI with stolen credentials to gain useful information from an operational cloud environment, such as specific services, resources, and features."
  },
  {
    "id": "T1539",
    "name": "Steal Web Session Cookie",
    "tactics": [
      "Credential Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1539",
    "summary": "An adversary may steal web application or service session cookies and use them to gain access to web applications or Internet services as an authenticated user without needing credentials."
  },
  {
    "id": "T1542",
    "name": "Pre-OS Boot",
    "tactics": [
      "Stealth",
      "Persistence"
    ],
    "url": "https://attack.mitre.org/techniques/T1542",
    "summary": "Adversaries may abuse Pre-OS Boot mechanisms as a way to establish persistence on a system."
  },
  {
    "id": "T1543",
    "name": "Create or Modify System Process",
    "tactics": [
      "Persistence",
      "Privilege Escalation"
    ],
    "url": "https://attack.mitre.org/techniques/T1543",
    "summary": "Adversaries may create or modify system-level processes to repeatedly execute malicious payloads as part of persistence."
  },
  {
    "id": "T1543.003",
    "name": "Windows Service",
    "tactics": [
      "Persistence",
      "Privilege Escalation"
    ],
    "url": "https://attack.mitre.org/techniques/T1543/003",
    "summary": "Adversaries may create or modify Windows services to repeatedly execute malicious payloads as part of persistence."
  },
  {
    "id": "T1546",
    "name": "Event Triggered Execution",
    "tactics": [
      "Privilege Escalation",
      "Persistence"
    ],
    "url": "https://attack.mitre.org/techniques/T1546",
    "summary": "Adversaries may establish persistence and/or elevate privileges using system mechanisms that trigger execution based on specific events."
  },
  {
    "id": "T1547",
    "name": "Boot or Logon Autostart Execution",
    "tactics": [
      "Persistence",
      "Privilege Escalation"
    ],
    "url": "https://attack.mitre.org/techniques/T1547",
    "summary": "Adversaries may configure system settings to automatically execute a program during system boot or logon to maintain persistence or gain higher-level privileges on compromised systems."
  },
  {
    "id": "T1548",
    "name": "Abuse Elevation Control Mechanism",
    "tactics": [
      "Privilege Escalation"
    ],
    "url": "https://attack.mitre.org/techniques/T1548",
    "summary": "Adversaries may circumvent mechanisms designed to control privilege elevation to gain higher-level permissions."
  },
  {
    "id": "T1550",
    "name": "Use Alternate Authentication Material",
    "tactics": [
      "Lateral Movement"
    ],
    "url": "https://attack.mitre.org/techniques/T1550",
    "summary": "Adversaries may use alternate authentication material, such as password hashes, Kerberos tickets, and application access tokens, in order to move laterally within an environment and bypass normal system access controls."
  },
  {
    "id": "T1550.002",
    "name": "Pass the Hash",
    "tactics": [
      "Lateral Movement"
    ],
    "url": "https://attack.mitre.org/techniques/T1550/002",
    "summary": "Adversaries may “pass the hash” using stolen password hashes to move laterally within an environment, bypassing normal system access controls."
  },
  {
    "id": "T1552",
    "name": "Unsecured Credentials",
    "tactics": [
      "Credential Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1552",
    "summary": "Adversaries may search compromised systems to find and obtain insecurely stored credentials."
  },
  {
    "id": "T1553",
    "name": "Subvert Trust Controls",
    "tactics": [
      "Defense Impairment"
    ],
    "url": "https://attack.mitre.org/techniques/T1553",
    "summary": "Adversaries may undermine security controls that will either warn users of untrusted activity or prevent execution of untrusted programs."
  },
  {
    "id": "T1554",
    "name": "Compromise Host Software Binary",
    "tactics": [
      "Persistence"
    ],
    "url": "https://attack.mitre.org/techniques/T1554",
    "summary": "Adversaries may modify host software binaries to establish persistent access to systems."
  },
  {
    "id": "T1555",
    "name": "Credentials from Password Stores",
    "tactics": [
      "Credential Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1555",
    "summary": "Adversaries may search for common password storage locations to obtain user credentials."
  },
  {
    "id": "T1556",
    "name": "Modify Authentication Process",
    "tactics": [
      "Defense Impairment",
      "Persistence",
      "Credential Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1556",
    "summary": "Adversaries may modify authentication mechanisms and processes to access user credentials or enable otherwise unwarranted access to accounts."
  },
  {
    "id": "T1557",
    "name": "Adversary-in-the-Middle",
    "tactics": [
      "Credential Access",
      "Collection"
    ],
    "url": "https://attack.mitre.org/techniques/T1557",
    "summary": "Adversaries may attempt to position themselves between two or more networked devices using an adversary-in-the-middle (AiTM) technique to support follow-on behaviors such as Network Sniffing, Transmitted Data Manipulation, or replay…"
  },
  {
    "id": "T1558",
    "name": "Steal or Forge Kerberos Tickets",
    "tactics": [
      "Credential Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1558",
    "summary": "Adversaries may attempt to subvert Kerberos authentication by stealing or forging Kerberos tickets to enable Pass the Ticket."
  },
  {
    "id": "T1559",
    "name": "Inter-Process Communication",
    "tactics": [
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1559",
    "summary": "Adversaries may abuse inter-process communication (IPC) mechanisms for local code or command execution."
  },
  {
    "id": "T1560",
    "name": "Archive Collected Data",
    "tactics": [
      "Collection"
    ],
    "url": "https://attack.mitre.org/techniques/T1560",
    "summary": "An adversary may compress and/or encrypt data that is collected prior to exfiltration."
  },
  {
    "id": "T1561",
    "name": "Disk Wipe",
    "tactics": [
      "Impact"
    ],
    "url": "https://attack.mitre.org/techniques/T1561",
    "summary": "Adversaries may wipe or corrupt raw disk data on specific systems or in large numbers in a network to interrupt availability to system and network resources."
  },
  {
    "id": "T1563",
    "name": "Remote Service Session Hijacking",
    "tactics": [
      "Lateral Movement"
    ],
    "url": "https://attack.mitre.org/techniques/T1563",
    "summary": "Adversaries may take control of preexisting sessions with remote services to move laterally in an environment."
  },
  {
    "id": "T1564",
    "name": "Hide Artifacts",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1564",
    "summary": "Adversaries may attempt to hide artifacts associated with their behaviors to evade detection."
  },
  {
    "id": "T1564.004",
    "name": "NTFS File Attributes",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1564/004",
    "summary": "Adversaries may use NTFS file attributes to hide their malicious data in order to evade detection."
  },
  {
    "id": "T1565",
    "name": "Data Manipulation",
    "tactics": [
      "Impact"
    ],
    "url": "https://attack.mitre.org/techniques/T1565",
    "summary": "Adversaries may insert, delete, or manipulate data in order to influence external outcomes or hide activity, thus threatening the integrity of the data."
  },
  {
    "id": "T1566",
    "name": "Phishing",
    "tactics": [
      "Initial Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1566",
    "summary": "Adversaries may send phishing messages to gain access to victim systems."
  },
  {
    "id": "T1567",
    "name": "Exfiltration Over Web Service",
    "tactics": [
      "Exfiltration"
    ],
    "url": "https://attack.mitre.org/techniques/T1567",
    "summary": "Adversaries may use an existing, legitimate external Web service to exfiltrate data rather than their primary command and control channel."
  },
  {
    "id": "T1568",
    "name": "Dynamic Resolution",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1568",
    "summary": "Adversaries may dynamically establish connections to command and control infrastructure to evade common detections and remediations."
  },
  {
    "id": "T1568.002",
    "name": "Domain Generation Algorithms",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1568/002",
    "summary": "Adversaries may make use of Domain Generation Algorithms (DGAs) to dynamically identify a destination domain for command and control traffic rather than relying on a list of static IP addresses or domains."
  },
  {
    "id": "T1569",
    "name": "System Services",
    "tactics": [
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1569",
    "summary": "Adversaries may abuse system services or daemons to execute commands or programs."
  },
  {
    "id": "T1570",
    "name": "Lateral Tool Transfer",
    "tactics": [
      "Lateral Movement"
    ],
    "url": "https://attack.mitre.org/techniques/T1570",
    "summary": "Adversaries may transfer tools or other files between systems in a compromised environment."
  },
  {
    "id": "T1571",
    "name": "Non-Standard Port",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1571",
    "summary": "Adversaries may communicate using a protocol and port pairing that are typically not associated."
  },
  {
    "id": "T1572",
    "name": "Protocol Tunneling",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1572",
    "summary": "Adversaries may tunnel network communications to and from a victim system within a separate protocol to avoid detection/network filtering and/or enable access to otherwise unreachable systems."
  },
  {
    "id": "T1573",
    "name": "Encrypted Channel",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1573",
    "summary": "Adversaries may employ an encryption algorithm to conceal command and control traffic rather than relying on any inherent protections provided by a communication protocol."
  },
  {
    "id": "T1574",
    "name": "Hijack Execution Flow",
    "tactics": [
      "Stealth",
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1574",
    "summary": "Adversaries may execute their own malicious payloads by hijacking the way operating systems run programs."
  },
  {
    "id": "T1578",
    "name": "Modify Cloud Compute Infrastructure",
    "tactics": [
      "Defense Impairment"
    ],
    "url": "https://attack.mitre.org/techniques/T1578",
    "summary": "An adversary may attempt to modify a cloud account's compute service infrastructure to evade defenses."
  },
  {
    "id": "T1580",
    "name": "Cloud Infrastructure Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1580",
    "summary": "An adversary may attempt to discover infrastructure and resources that are available within an infrastructure-as-a-service (IaaS) environment."
  },
  {
    "id": "T1583",
    "name": "Acquire Infrastructure",
    "tactics": [
      "Resource Development"
    ],
    "url": "https://attack.mitre.org/techniques/T1583",
    "summary": "Adversaries may buy, lease, rent, or obtain infrastructure that can be used during targeting."
  },
  {
    "id": "T1584",
    "name": "Compromise Infrastructure",
    "tactics": [
      "Resource Development"
    ],
    "url": "https://attack.mitre.org/techniques/T1584",
    "summary": "Adversaries may compromise third-party infrastructure that can be used during targeting."
  },
  {
    "id": "T1585",
    "name": "Establish Accounts",
    "tactics": [
      "Resource Development"
    ],
    "url": "https://attack.mitre.org/techniques/T1585",
    "summary": "Adversaries may create and cultivate accounts with services that can be used during targeting."
  },
  {
    "id": "T1586",
    "name": "Compromise Accounts",
    "tactics": [
      "Resource Development"
    ],
    "url": "https://attack.mitre.org/techniques/T1586",
    "summary": "Adversaries may compromise accounts with services that can be used during targeting."
  },
  {
    "id": "T1587",
    "name": "Develop Capabilities",
    "tactics": [
      "Resource Development"
    ],
    "url": "https://attack.mitre.org/techniques/T1587",
    "summary": "Adversaries may build capabilities that can be used during targeting."
  },
  {
    "id": "T1588",
    "name": "Obtain Capabilities",
    "tactics": [
      "Resource Development"
    ],
    "url": "https://attack.mitre.org/techniques/T1588",
    "summary": "Adversaries may buy and/or steal capabilities that can be used during targeting."
  },
  {
    "id": "T1589",
    "name": "Gather Victim Identity Information",
    "tactics": [
      "Reconnaissance"
    ],
    "url": "https://attack.mitre.org/techniques/T1589",
    "summary": "Adversaries may gather information about the victim's identity that can be used during targeting."
  },
  {
    "id": "T1590",
    "name": "Gather Victim Network Information",
    "tactics": [
      "Reconnaissance"
    ],
    "url": "https://attack.mitre.org/techniques/T1590",
    "summary": "Adversaries may gather information about the victim's networks that can be used during targeting."
  },
  {
    "id": "T1591",
    "name": "Gather Victim Org Information",
    "tactics": [
      "Reconnaissance"
    ],
    "url": "https://attack.mitre.org/techniques/T1591",
    "summary": "Adversaries may gather information about the victim's organization that can be used during targeting."
  },
  {
    "id": "T1592",
    "name": "Gather Victim Host Information",
    "tactics": [
      "Reconnaissance"
    ],
    "url": "https://attack.mitre.org/techniques/T1592",
    "summary": "Adversaries may gather information about the victim's hosts that can be used during targeting."
  },
  {
    "id": "T1593",
    "name": "Search Open Websites/Domains",
    "tactics": [
      "Reconnaissance"
    ],
    "url": "https://attack.mitre.org/techniques/T1593",
    "summary": "Adversaries may search freely available websites and/or domains for information about victims that can be used during targeting."
  },
  {
    "id": "T1594",
    "name": "Search Victim-Owned Websites",
    "tactics": [
      "Reconnaissance"
    ],
    "url": "https://attack.mitre.org/techniques/T1594",
    "summary": "Adversaries may search websites owned by the victim for information that can be used during targeting."
  },
  {
    "id": "T1595",
    "name": "Active Scanning",
    "tactics": [
      "Reconnaissance"
    ],
    "url": "https://attack.mitre.org/techniques/T1595",
    "summary": "Adversaries may execute active reconnaissance scans to gather information that can be used during targeting."
  },
  {
    "id": "T1596",
    "name": "Search Open Technical Databases",
    "tactics": [
      "Reconnaissance"
    ],
    "url": "https://attack.mitre.org/techniques/T1596",
    "summary": "Adversaries may search freely available technical databases for information about victims that can be used during targeting."
  },
  {
    "id": "T1597",
    "name": "Search Closed Sources",
    "tactics": [
      "Reconnaissance"
    ],
    "url": "https://attack.mitre.org/techniques/T1597",
    "summary": "Adversaries may search and gather information about victims from closed (e.g., paid, private, or otherwise not freely available) sources that can be used during targeting."
  },
  {
    "id": "T1598",
    "name": "Phishing for Information",
    "tactics": [
      "Reconnaissance"
    ],
    "url": "https://attack.mitre.org/techniques/T1598",
    "summary": "Adversaries may send phishing messages to elicit sensitive information that can be used during targeting."
  },
  {
    "id": "T1599",
    "name": "Network Boundary Bridging",
    "tactics": [
      "Defense Impairment"
    ],
    "url": "https://attack.mitre.org/techniques/T1599",
    "summary": "Adversaries may bridge network boundaries by compromising perimeter network devices or internal devices responsible for network segmentation."
  },
  {
    "id": "T1600",
    "name": "Weaken Encryption",
    "tactics": [
      "Defense Impairment"
    ],
    "url": "https://attack.mitre.org/techniques/T1600",
    "summary": "Adversaries may compromise a network device’s encryption capability in order to bypass encryption that would otherwise protect data communications."
  },
  {
    "id": "T1601",
    "name": "Modify System Image",
    "tactics": [
      "Defense Impairment"
    ],
    "url": "https://attack.mitre.org/techniques/T1601",
    "summary": "Adversaries may make changes to the operating system of embedded network devices to weaken defenses and provide new capabilities for themselves."
  },
  {
    "id": "T1602",
    "name": "Data from Configuration Repository",
    "tactics": [
      "Collection"
    ],
    "url": "https://attack.mitre.org/techniques/T1602",
    "summary": "Adversaries may collect data related to managed devices from configuration repositories."
  },
  {
    "id": "T1606",
    "name": "Forge Web Credentials",
    "tactics": [
      "Credential Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1606",
    "summary": "Adversaries may forge credential materials that can be used to gain access to web applications or Internet services."
  },
  {
    "id": "T1608",
    "name": "Stage Capabilities",
    "tactics": [
      "Resource Development"
    ],
    "url": "https://attack.mitre.org/techniques/T1608",
    "summary": "Adversaries may upload, install, or otherwise set up capabilities that can be used during targeting."
  },
  {
    "id": "T1609",
    "name": "Container Administration Command",
    "tactics": [
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1609",
    "summary": "Adversaries may abuse a container administration service to execute commands within a container."
  },
  {
    "id": "T1610",
    "name": "Deploy Container",
    "tactics": [
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1610",
    "summary": "Adversaries may deploy a container into an environment to facilitate execution or evade defenses."
  },
  {
    "id": "T1611",
    "name": "Escape to Host",
    "tactics": [
      "Privilege Escalation"
    ],
    "url": "https://attack.mitre.org/techniques/T1611",
    "summary": "Adversaries may break out of a container or virtualized environment to gain access to the underlying host."
  },
  {
    "id": "T1612",
    "name": "Build Image on Host",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1612",
    "summary": "Adversaries may build a container image directly on a host to bypass defenses that monitor for the retrieval of malicious images from a public registry."
  },
  {
    "id": "T1613",
    "name": "Container and Resource Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1613",
    "summary": "Adversaries may attempt to discover containers and other resources that are available within a containers environment."
  },
  {
    "id": "T1614",
    "name": "System Location Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1614",
    "summary": "Adversaries may gather information in an attempt to calculate the geographical location of a victim host."
  },
  {
    "id": "T1615",
    "name": "Group Policy Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1615",
    "summary": "Adversaries may gather information on Group Policy settings to identify paths for privilege escalation, security measures applied within a domain, and to discover patterns in domain objects that can be manipulated or used to blend in…"
  },
  {
    "id": "T1619",
    "name": "Cloud Storage Object Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1619",
    "summary": "Adversaries may enumerate objects in cloud storage infrastructure."
  },
  {
    "id": "T1620",
    "name": "Reflective Code Loading",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1620",
    "summary": "Adversaries may reflectively load code into a process in order to conceal the execution of malicious payloads."
  },
  {
    "id": "T1621",
    "name": "Multi-Factor Authentication Request Generation",
    "tactics": [
      "Credential Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1621",
    "summary": "Adversaries may attempt to bypass multi-factor authentication (MFA) mechanisms and gain access to accounts by generating MFA requests sent to users."
  },
  {
    "id": "T1622",
    "name": "Debugger Evasion",
    "tactics": [
      "Stealth",
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1622",
    "summary": "Adversaries may employ various means to detect and avoid debuggers."
  },
  {
    "id": "T1647",
    "name": "Plist File Modification",
    "tactics": [
      "Defense Impairment"
    ],
    "url": "https://attack.mitre.org/techniques/T1647",
    "summary": "Adversaries may modify property list files (plist files) to enable other malicious activity, while also potentially evading and bypassing system defenses."
  },
  {
    "id": "T1648",
    "name": "Serverless Execution",
    "tactics": [
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1648",
    "summary": "Adversaries may abuse serverless computing, integration, and automation services to execute arbitrary code in cloud environments."
  },
  {
    "id": "T1649",
    "name": "Steal or Forge Authentication Certificates",
    "tactics": [
      "Credential Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1649",
    "summary": "Adversaries may steal or forge certificates used for authentication to access remote systems or resources."
  },
  {
    "id": "T1650",
    "name": "Acquire Access",
    "tactics": [
      "Resource Development"
    ],
    "url": "https://attack.mitre.org/techniques/T1650",
    "summary": "Adversaries may purchase or otherwise acquire an existing access to a target system or network."
  },
  {
    "id": "T1651",
    "name": "Cloud Administration Command",
    "tactics": [
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1651",
    "summary": "Adversaries may abuse cloud management services to execute commands within virtual machines."
  },
  {
    "id": "T1652",
    "name": "Device Driver Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1652",
    "summary": "Adversaries may attempt to enumerate local device drivers on a victim host."
  },
  {
    "id": "T1653",
    "name": "Power Settings",
    "tactics": [
      "Persistence"
    ],
    "url": "https://attack.mitre.org/techniques/T1653",
    "summary": "Adversaries may impair a system's ability to hibernate, reboot, or shut down in order to extend access to infected machines."
  },
  {
    "id": "T1654",
    "name": "Log Enumeration",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1654",
    "summary": "Adversaries may enumerate system and service logs to find useful data."
  },
  {
    "id": "T1657",
    "name": "Financial Theft",
    "tactics": [
      "Impact"
    ],
    "url": "https://attack.mitre.org/techniques/T1657",
    "summary": "Adversaries may steal monetary resources from targets through extortion, social engineering, technical theft, or other methods aimed at their own financial gain at the expense of the availability of these resources for victims."
  },
  {
    "id": "T1659",
    "name": "Content Injection",
    "tactics": [
      "Initial Access",
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1659",
    "summary": "Adversaries may gain access and continuously communicate with victims by injecting malicious content into systems through online network traffic."
  },
  {
    "id": "T1665",
    "name": "Hide Infrastructure",
    "tactics": [
      "Command and Control"
    ],
    "url": "https://attack.mitre.org/techniques/T1665",
    "summary": "Adversaries may manipulate network traffic in order to hide and evade detection of their C2 infrastructure."
  },
  {
    "id": "T1666",
    "name": "Modify Cloud Resource Hierarchy",
    "tactics": [
      "Defense Impairment"
    ],
    "url": "https://attack.mitre.org/techniques/T1666",
    "summary": "Adversaries may attempt to modify hierarchical structures in infrastructure-as-a-service (IaaS) environments in order to evade defenses."
  },
  {
    "id": "T1667",
    "name": "Email Bombing",
    "tactics": [
      "Impact"
    ],
    "url": "https://attack.mitre.org/techniques/T1667",
    "summary": "Adversaries may flood targeted email addresses with an overwhelming volume of messages."
  },
  {
    "id": "T1668",
    "name": "Exclusive Control",
    "tactics": [
      "Persistence"
    ],
    "url": "https://attack.mitre.org/techniques/T1668",
    "summary": "Adversaries who successfully compromise a system may attempt to maintain persistence by “closing the door” behind them – in other words, by preventing other threat actors from initially accessing or maintaining a foothold on the same…"
  },
  {
    "id": "T1669",
    "name": "Wi-Fi Networks",
    "tactics": [
      "Initial Access"
    ],
    "url": "https://attack.mitre.org/techniques/T1669",
    "summary": "Adversaries may gain initial access to target systems by connecting to wireless networks."
  },
  {
    "id": "T1671",
    "name": "Cloud Application Integration",
    "tactics": [
      "Persistence"
    ],
    "url": "https://attack.mitre.org/techniques/T1671",
    "summary": "Adversaries may achieve persistence by leveraging OAuth application integrations in a software-as-a-service environment."
  },
  {
    "id": "T1673",
    "name": "Virtual Machine Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1673",
    "summary": "An adversary may attempt to enumerate running virtual machines (VMs) after gaining access to a host or hypervisor."
  },
  {
    "id": "T1674",
    "name": "Input Injection",
    "tactics": [
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1674",
    "summary": "Adversaries may simulate keystrokes on a victim’s computer by various means to perform any type of action on behalf of the user, such as launching the command interpreter using keyboard shortcuts, typing an inline script to be executed,…"
  },
  {
    "id": "T1675",
    "name": "ESXi Administration Command",
    "tactics": [
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1675",
    "summary": "Adversaries may abuse ESXi administration services to execute commands on guest machines hosted within an ESXi virtual environment."
  },
  {
    "id": "T1677",
    "name": "Poisoned Pipeline Execution",
    "tactics": [
      "Execution"
    ],
    "url": "https://attack.mitre.org/techniques/T1677",
    "summary": "Adversaries may manipulate continuous integration / continuous development (CI/CD) processes by injecting malicious code into the build process."
  },
  {
    "id": "T1678",
    "name": "Delay Execution",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1678",
    "summary": "Adversaries may employ various time-based methods to evade detection and analysis."
  },
  {
    "id": "T1679",
    "name": "Selective Exclusion",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1679",
    "summary": "Adversaries may intentionally exclude certain files, folders, directories, file types, or system components from encryption or tampering during a ransomware or malicious payload execution."
  },
  {
    "id": "T1680",
    "name": "Local Storage Discovery",
    "tactics": [
      "Discovery"
    ],
    "url": "https://attack.mitre.org/techniques/T1680",
    "summary": "Adversaries may enumerate local drives, disks, and/or volumes and their attributes like total or free space and volume serial number."
  },
  {
    "id": "T1681",
    "name": "Search Threat Vendor Data",
    "tactics": [
      "Reconnaissance"
    ],
    "url": "https://attack.mitre.org/techniques/T1681",
    "summary": "Threat actors may seek information/indicators from closed or open threat intelligence sources gathered about their own campaigns, as well as those conducted by other adversaries that may align with their target industries,…"
  },
  {
    "id": "T1682",
    "name": "Query Public AI Services",
    "tactics": [
      "Reconnaissance"
    ],
    "url": "https://attack.mitre.org/techniques/T1682",
    "summary": "Adversaries may query publicly accessible artificial intelligence (AI) services, such as large language models (LLMs), to support targeting and operations."
  },
  {
    "id": "T1683",
    "name": "Generate Content",
    "tactics": [
      "Resource Development"
    ],
    "url": "https://attack.mitre.org/techniques/T1683",
    "summary": "Adversaries may create or generate content to support targeting and operations."
  },
  {
    "id": "T1684",
    "name": "Social Engineering",
    "tactics": [
      "Stealth"
    ],
    "url": "https://attack.mitre.org/techniques/T1684",
    "summary": "Adversaries may use social engineering techniques to influence users to take actions that result in unauthorized access, approval of changes, disclosure of sensitive information, or execution of adversary-supplied instructions (i.e.,…"
  },
  {
    "id": "T1685",
    "name": "Disable or Modify Tools",
    "tactics": [
      "Defense Impairment"
    ],
    "url": "https://attack.mitre.org/techniques/T1685",
    "summary": "Adversaries may disable, degrade, or tamper with security tools or applications (e.g., endpoint detection and response (EDR) tools, intrusion detection systems (IDS), antivirus, logging agents, sensors, etc.) to impair or reduce…"
  },
  {
    "id": "T1686",
    "name": "Disable or Modify System Firewall",
    "tactics": [
      "Defense Impairment"
    ],
    "url": "https://attack.mitre.org/techniques/T1686",
    "summary": "Adversaries may disable or modify host-based or network firewalls to impair defensive mechanisms and enable further action."
  },
  {
    "id": "T1687",
    "name": "Exploitation for Defense Impairment",
    "tactics": [
      "Defense Impairment"
    ],
    "url": "https://attack.mitre.org/techniques/T1687",
    "summary": "Adversaries may exploit vulnerabilities in security software, infrastructure, or defensive components to degrade, disable, or otherwise continue to impair their ability to prevent, detect, or respond to malicious activity."
  },
  {
    "id": "T1688",
    "name": "Safe Mode Boot",
    "tactics": [
      "Defense Impairment"
    ],
    "url": "https://attack.mitre.org/techniques/T1688",
    "summary": "Adversaries may abuse Windows safe mode to disable endpoint defenses."
  },
  {
    "id": "T1689",
    "name": "Downgrade Attack",
    "tactics": [
      "Defense Impairment"
    ],
    "url": "https://attack.mitre.org/techniques/T1689",
    "summary": "Adversaries may downgrade or use a version of system features that may be outdated, vulnerable, and/or does not support updated security controls."
  },
  {
    "id": "T1690",
    "name": "Prevent Command History Logging",
    "tactics": [
      "Defense Impairment"
    ],
    "url": "https://attack.mitre.org/techniques/T1690",
    "summary": "Adversaries may impair command history logging to hide commands they run on a compromised system."
  }
];
